version: "3.7"
services: 
    youtube-downloader-client-dev:
        stdin_open: true
        tty: true
        container_name: youtube-downloader-client-dev
        build:
          context: ./
          dockerfile: ./Dockerfile
        ports:
          - "3000:3000"
        volumes: 
            - .:/app
            - /app/node_modules
        environment:
          - CHOKIDAR_USEPOLLING=true